# Generated by Django 4.1.3 on 2022-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modifed_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
