# Generated by Django 4.1.3 on 2022-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='modifed_date',
            new_name='modified_date',
        ),
    ]
