# Generated by Django 4.1.3 on 2023-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_slug_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=221, unique=True),
        ),
    ]
